language: rust
rust:
  - 1.21.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose
  - cargo build --verbose --example=barebone_blink
  - cargo build --verbose --example=barebone_parallel_blink
  - cargo build --verbose --example=pwm_generator
  - cargo doc
